### PR TITLE
Added a post about orchestration

### PR DESCRIPTION
**Pull request by gen1us2k**
I have no idea how to translate zero-time deployment to Kyrgyz :(

### CODE REVIEW

**Comment by MirlanJA** [comment]
Maybe "Тынымсыз (zero-time) деплоймент" ?

**Comment by gen1us2k** [comment]
@MirlanJA After a conversation within the DevKurultai community I decided to not translate some English terms such as Zero-time deployment, pod, deployment, statefulset, daemonset, replicaset, and other either Kubernetes or Industry specific terms. The best solution, in that case, would be an explanation of the term and use it as is. Maybe add some transliterated versions such as деплой, зиротайм деплоймент, под, нода, репликасет because they are more or less international and using them would be helpful for the learner. At least they can pass interview on Kyrgyz, Russian, or English language.

I'll add the description to the readme and update some guides. What do you think?

**Comment by ibakirov** [comment]
@gen1us2k definitely industry specific terms should be kept as is: pod, statefulset, daemonset, replicaset

**Comment by MirlanJA** [comment]
@gen1us2k I totally agree

**Review by MirlanJA — APPROVED** [review]

**Pull request merged**
